### ISSUE TITLE
hot module reload

### ISSUE THREAD

**Issue by 312977** [johndab/electron.net-vue#2]
thanks for your demo
but this demo can not hot module reload
can  you  help me   thank you

**Comment by johndab** [comment]
Hi!

Hot reload should work in the demo, please try starting vue server in front-end and checking if hot reloading works on localhost:8080 in the browser.

Make sure you comment-out the target in vue.config.js before doing that:
```js
module.exports = {
  configureWebpack: {
    // target: 'electron-renderer',
  },
};
```
